### ISSUE TITLE
Contributing to Documentation Directions

### ISSUE THREAD

**Issue by cruth7182** [Kitty-Inu-DAO/Governance-Docs#4]
**Is your feature request related to a problem? Please describe.**
When attempting to create a new branch (after cloning the repository), I had to initialize the repository using git init.

**Describe the solution you'd like**
Perhaps add in the need for the git init command prior to the git checkout -b your-branch-name command.

**Describe alternatives you've considered**
Uhhhh....none :)

**Additional context**
I may not know what I'm talking about completely, but initializing the repository helped me to successfully create a new branch. I'm a very basic coder, lol.

![image](https://github.com/Kitty-Inu-DAO/Governance-Docs/assets/100045023/394c2dc3-9ea6-4dae-8bbd-9941243b4315)

**Comment by axtina** [comment]
@cruth7182 

The process of cloning a repository encompasses the initialization - I.e. when you run:

```
git clone <repo>
```

it automatically creates a new directory, initializes a .git directory inside it, pulls down all the data for that repository, and checks out a working copy of the latest version. 

it would be good to know what steps you took to get the state where you needed to reinitialize git and use that to make the docs more clear so others don't have the same issue

**Comment by cruth7182** [comment]
Thanks for your speedy reply. I'll try to replicate the issue tomorrow morning, and see how it goes.

**Comment by cruth7182** [comment]
I was not able to replicate the issue, so I am thinking it was my error. Thanks for the reply!
